package controller

import (
	"context"
	"testing"

	policyAPI "github.com/giantswarm/policy-api/api/v1alpha1"
	policiesv1 "github.com/kyverno/api/api/policies.kyverno.io/v1"
	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	kyvernov2 "github.com/kyverno/kyverno/api/kyverno/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/client/interceptor"

	"github.com/giantswarm/exception-recommender/internal/migration"
)

const (
	testBridgeNamespace = "policy-exceptions"
	// testPolicyName is the ClusterPolicy every source exempts; see nonrootPolicy.
	testPolicyName          = "require-run-as-nonroot"
	ruleRunAsNonRoot        = "run-as-non-root"
	ruleRunAsNonRootAutogen = "autogen-run-as-non-root"
	kindPod                 = "Pod"
)

// sourceKey is the default source's key and bridgeKey its bridge's.
var (
	sourceKey = types.NamespacedName{Namespace: "giantswarm", Name: "cilium"}
	bridgeKey = types.NamespacedName{Namespace: testBridgeNamespace, Name: "cilium" + migration.BridgeSuffix}
)

func unitScheme(t *testing.T) *runtime.Scheme {
	t.Helper()
	s := runtime.NewScheme()
	for _, add := range []func(*runtime.Scheme) error{
		kyvernov1.Install, kyvernov2.Install, policiesv1.Install, policyAPI.AddToScheme, apiextensionsv1.AddToScheme,
	} {
		require.NoError(t, add(s))
	}
	return s
}

// newClient returns a fake client holding objects.
func newClient(t *testing.T, objects ...client.Object) client.WithWatch {
	t.Helper()
	return fake.NewClientBuilder().WithScheme(unitScheme(t)).WithObjects(objects...).Build()
}

// newClientWith returns a fake client holding objects whose calls go through funcs first.
func newClientWith(t *testing.T, funcs interceptor.Funcs, objects ...client.Object) client.WithWatch {
	t.Helper()
	return fake.NewClientBuilder().WithScheme(unitScheme(t)).WithObjects(objects...).WithInterceptorFuncs(funcs).Build()
}

// legacyCRD is a healthy legacy PolicyException CRD serving kyverno.io/v2, which bridge deletion requires.
func legacyCRD() *apiextensionsv1.CustomResourceDefinition {
	return &apiextensionsv1.CustomResourceDefinition{
		ObjectMeta: metav1.ObjectMeta{Name: migration.LegacyCRDName},
		Spec: apiextensionsv1.CustomResourceDefinitionSpec{
			Versions: []apiextensionsv1.CustomResourceDefinitionVersion{{Name: "v2", Served: true, Storage: true}},
		},
	}
}

// nonrootPolicy is the ClusterPolicy the sources exempt, with a rule and its autogen rule.
func nonrootPolicy() *kyvernov1.ClusterPolicy {
	p := &kyvernov1.ClusterPolicy{ObjectMeta: metav1.ObjectMeta{Name: testPolicyName}}
	p.Spec.Rules = []kyvernov1.Rule{{Name: ruleRunAsNonRoot}, {Name: ruleRunAsNonRootAutogen}}
	return p
}

// exactSource exempts every rule of nonrootPolicy, so it translates exactly into a bridge with one
// policy and two targets.
func exactSource() *kyvernov2.PolicyException {
	return sourceExempting(ruleRunAsNonRoot, ruleRunAsNonRootAutogen)
}

// lossySource leaves out nonrootPolicy's autogen rule; a bridge would exempt more than it does.
func lossySource() *kyvernov2.PolicyException {
	return sourceExempting(ruleRunAsNonRoot)
}

// unsupportedSource selects by label, which a bridge cannot express.
func unsupportedSource() *kyvernov2.PolicyException {
	src := exactSource()
	src.Spec.Match.Any[0].Selector = &metav1.LabelSelector{MatchLabels: map[string]string{"app": "cilium"}}
	return src
}

// kpoSource was generated by kyverno-policy-operator and is never bridged.
func kpoSource() *kyvernov2.PolicyException {
	src := exactSource()
	src.Labels = map[string]string{migration.ManagedByLabel: migration.KPOComponentName}
	return src
}

func sourceExempting(ruleNames ...string) *kyvernov2.PolicyException {
	src := &kyvernov2.PolicyException{ObjectMeta: metav1.ObjectMeta{Name: sourceKey.Name, Namespace: sourceKey.Namespace}}
	src.Spec.Exceptions = []kyvernov2.Exception{{PolicyName: testPolicyName, RuleNames: ruleNames}}
	src.Spec.Match.Any = kyvernov1.ResourceFilters{{ResourceDescription: kyvernov1.ResourceDescription{
		Kinds: []string{"DaemonSet", kindPod}, Namespaces: []string{"kube-system"}, Names: []string{"cilium*"},
	}}}
	return src
}

// withName renames src, which also renames its bridge.
func withName(src *kyvernov2.PolicyException, name string) *kyvernov2.PolicyException {
	src.Name = name
	return src
}

// inNamespace moves src to namespace; its bridge name stays the same.
func inNamespace(src *kyvernov2.PolicyException, namespace string) *kyvernov2.PolicyException {
	src.Namespace = namespace
	return src
}

// bridgeOf is the bridge exception-recommender wrote for src, with an empty spec so that a rewrite
// is visible.
func bridgeOf(src *kyvernov2.PolicyException) *policyAPI.PolicyException {
	bridge := handWrittenBridgeFor(src)
	bridge.Labels = map[string]string{migration.ManagedByLabel: migration.ComponentName}
	return bridge
}

// handWrittenBridgeFor looks like src's bridge, name and migrated-from annotation included, but lacks
// the managed-by label: someone else's object that exception-recommender must never touch.
func handWrittenBridgeFor(src *kyvernov2.PolicyException) *policyAPI.PolicyException {
	return &policyAPI.PolicyException{
		ObjectMeta: metav1.ObjectMeta{
			Name:        migration.BridgeName(src),
			Namespace:   testBridgeNamespace,
			Annotations: map[string]string{migration.AnnotationMigratedFrom: migration.SourceKey(src)},
		},
		Spec: policyAPI.PolicyExceptionSpec{Policies: []string{}, Targets: []policyAPI.Target{}},
	}
}

// getBridge returns the object at bridgeKey, or false when there is none.
func getBridge(t *testing.T, c client.Client) (*policyAPI.PolicyException, bool) {
	t.Helper()
	var bridge policyAPI.PolicyException
	err := c.Get(context.Background(), bridgeKey, &bridge)
	if apierrors.IsNotFound(err) {
		return nil, false
	}
	require.NoError(t, err)
	return &bridge, true
}

// requireBridge returns the object at bridgeKey and stops the test when there is none.
func requireBridge(t *testing.T, c client.Client) *policyAPI.PolicyException {
	t.Helper()
	bridge, ok := getBridge(t, c)
	require.True(t, ok, "no object at %s", bridgeKey)
	return bridge
}

func assertNoBridge(t *testing.T, c client.Client, msg string) {
	t.Helper()
	_, ok := getBridge(t, c)
	assert.False(t, ok, msg)
}

// assertBridgeUnchanged checks that the object at bridgeKey is still there and was not written since before.
func assertBridgeUnchanged(t *testing.T, c client.Client, before *policyAPI.PolicyException) {
	t.Helper()
	after, ok := getBridge(t, c)
	if assert.True(t, ok, "object at %s deleted", bridgeKey) {
		assert.Equal(t, before.ResourceVersion, after.ResourceVersion, "object at %s rewritten", bridgeKey)
	}
}
