package controller

import (
	"context"
	"errors"

	policyAPI "github.com/giantswarm/policy-api/api/v1alpha1"
	kyvernov2 "github.com/kyverno/kyverno/api/kyverno/v2"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	"sigs.k8s.io/controller-runtime/pkg/source"

	"github.com/giantswarm/exception-recommender/internal/migration"
)

var errNotOurBridge = errors.New("object exists and is not this source's bridge")

// LegacyExceptionReconciler keeps one Giant Swarm PolicyException ("bridge") per legacy kyverno.io
// PolicyException that can be translated exactly, and deletes it only when the source is deleted.
// It never writes Kyverno resources.
type LegacyExceptionReconciler struct {
	client.Client
	// APIReader reads from the API server, bypassing the cache, before a bridge is deleted.
	APIReader       client.Reader
	BridgeNamespace string
}

func (r *LegacyExceptionReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	src := kyvernov2.PolicyException{ObjectMeta: metav1.ObjectMeta{Name: req.Name, Namespace: req.Namespace}}
	logger := log.FromContext(ctx).WithValues("source", migration.SourceKey(&src))
	ctx = log.IntoContext(ctx, logger)

	if err := r.Get(ctx, req.NamespacedName, &src); err != nil {
		if !apierrors.IsNotFound(err) {
			logger.Error(err, "unable to get legacy PolicyException")
			return ctrl.Result{}, err
		}
		logger.V(1).Info("legacy PolicyException not found")
		return ctrl.Result{}, r.removeOrphanedBridge(ctx, req.NamespacedName)
	}
	if migration.IsManagedByKPO(&src) {
		logger.V(1).Info("legacy PolicyException generated by kyverno-policy-operator, skipping")
		return ctrl.Result{}, nil
	}

	status, err := migration.Evaluate(ctx, r.Client, r.BridgeNamespace, &src)
	if err != nil {
		TranslationErrors.WithLabelValues(ReasonLookupFailed).Inc()
		logger.Error(err, "unable to evaluate legacy PolicyException")
		return ctrl.Result{}, err
	}
	logger.V(1).Info("evaluated legacy PolicyException", "state", status.State, "reason", status.Reason)

	switch {
	case status.Write:
		return ctrl.Result{}, r.writeBridge(ctx, &src, status.Spec)
	case (status.State == migration.StateLossy || status.State == migration.StateUnsupported) && status.OwnsBridge(&src):
		// Keep the last good bridge rather than remove an exception that workloads may rely on.
		logger.Info("legacy PolicyException no longer translates exactly, keeping the last bridge unchanged",
			"bridge", client.ObjectKeyFromObject(status.Bridge), "state", status.State, "reason", status.Reason)
		return ctrl.Result{}, nil
	default:
		logger.V(1).Info("nothing to write", "state", status.State, "reason", status.Reason)
		return ctrl.Result{}, nil
	}
}

// writeBridge creates or updates the bridge for src. It only runs when Evaluate found no object of
// that name or one this controller wrote for src.
func (r *LegacyExceptionReconciler) writeBridge(ctx context.Context, src *kyvernov2.PolicyException, spec policyAPI.PolicyExceptionSpec) error {
	logger := log.FromContext(ctx)
	bridge := policyAPI.PolicyException{ObjectMeta: metav1.ObjectMeta{Name: migration.BridgeName(src), Namespace: r.BridgeNamespace}}

	op, err := controllerutil.CreateOrUpdate(ctx, r.Client, &bridge, func() error {
		if bridge.ResourceVersion != "" && !migration.IsBridgeFor(&bridge, migration.SourceKey(src)) {
			// Created by someone else since Evaluate looked; never take it over.
			return errNotOurBridge
		}
		if bridge.Labels == nil {
			bridge.Labels = map[string]string{}
		}
		bridge.Labels[migration.ManagedByLabel] = migration.ComponentName
		if bridge.Annotations == nil {
			bridge.Annotations = map[string]string{}
		}
		bridge.Annotations[migration.AnnotationMigratedFrom] = migration.SourceKey(src)
		bridge.Spec = spec
		return nil
	})
	if errors.Is(err, errNotOurBridge) {
		// A name collision, not an API failure: the next Evaluate reports it as such.
		logger.V(1).Info("object is not this source's bridge, leaving it alone", "bridge", client.ObjectKeyFromObject(&bridge))
		return nil
	}
	if err != nil {
		TranslationErrors.WithLabelValues(ReasonApplyFailed).Inc()
		logger.Error(err, "unable to write bridge", "bridge", client.ObjectKeyFromObject(&bridge))
		return err
	}
	if op == controllerutil.OperationResultNone {
		logger.V(1).Info("bridge unchanged", "bridge", client.ObjectKeyFromObject(&bridge))
		return nil
	}
	logger.Info("bridge written", "bridge", client.ObjectKeyFromObject(&bridge), "operation", op)
	return nil
}

// removeOrphanedBridge deletes the bridge of a source that is gone, after confirming with the API
// server that the source really is gone and that the legacy CRD is not being removed.
func (r *LegacyExceptionReconciler) removeOrphanedBridge(ctx context.Context, source types.NamespacedName) error {
	logger := log.FromContext(ctx)
	src := kyvernov2.PolicyException{ObjectMeta: metav1.ObjectMeta{Name: source.Name, Namespace: source.Namespace}}

	var bridge policyAPI.PolicyException
	key := types.NamespacedName{Namespace: r.BridgeNamespace, Name: migration.BridgeName(&src)}
	if err := r.Get(ctx, key, &bridge); err != nil {
		if apierrors.IsNotFound(err) {
			logger.V(1).Info("no bridge to remove", "bridge", key)
			return nil
		}
		logger.Error(err, "unable to get bridge", "bridge", key)
		return err
	}
	if !migration.IsBridgeFor(&bridge, migration.SourceKey(&src)) {
		logger.V(1).Info("object is not this source's bridge, leaving it alone", "bridge", key)
		return nil
	}

	gone, err := r.sourceGone(ctx, source)
	if err != nil || !gone {
		return err
	}
	return r.deleteBridge(ctx, &bridge)
}

// sourceGone confirms, reading from the API server, that the legacy CRD is healthy and the source
// is deleted. Bridges are never removed on the strength of a stale cache or a CRD being deleted.
func (r *LegacyExceptionReconciler) sourceGone(ctx context.Context, source types.NamespacedName) (bool, error) {
	logger := log.FromContext(ctx)

	var crd apiextensionsv1.CustomResourceDefinition
	if err := r.APIReader.Get(ctx, types.NamespacedName{Name: migration.LegacyCRDName}, &crd); err != nil {
		if apierrors.IsNotFound(err) {
			logger.Info("legacy PolicyException CRD not found, keeping bridge")
			return false, nil
		}
		logger.Error(err, "unable to get legacy PolicyException CRD, keeping bridge")
		return false, err
	}
	if !crd.DeletionTimestamp.IsZero() {
		logger.Info("legacy PolicyException CRD is being deleted, keeping bridge")
		return false, nil
	}
	if !servesV2(&crd) {
		// A NotFound for a version that is not served says nothing about the source.
		logger.Info("legacy PolicyException CRD does not serve kyverno.io/v2, keeping bridge")
		return false, nil
	}

	var src kyvernov2.PolicyException
	err := r.APIReader.Get(ctx, source, &src)
	switch {
	case err == nil:
		logger.V(1).Info("legacy PolicyException still exists on the API server, keeping bridge")
		return false, nil
	case apierrors.IsNotFound(err):
		return true, nil
	default:
		logger.Error(err, "unable to confirm legacy PolicyException is deleted, keeping bridge")
		return false, err
	}
}

// servesV2 reports whether crd serves kyverno.io/v2, the version sources are read with.
func servesV2(crd *apiextensionsv1.CustomResourceDefinition) bool {
	for _, version := range crd.Spec.Versions {
		if version.Name == "v2" && version.Served {
			return true
		}
	}
	return false
}

// deleteBridge deletes a bridge that IsBridgeFor confirmed was written for the source. The delete is
// pinned to that object, so one that changed or was recreated since the check is left alone.
func (r *LegacyExceptionReconciler) deleteBridge(ctx context.Context, bridge *policyAPI.PolicyException) error {
	logger := log.FromContext(ctx)
	key := client.ObjectKeyFromObject(bridge)
	if err := r.Delete(ctx, bridge, client.Preconditions{UID: &bridge.UID, ResourceVersion: &bridge.ResourceVersion}); err != nil {
		if apierrors.IsNotFound(err) {
			logger.V(1).Info("bridge already deleted", "bridge", key)
			return nil
		}
		if apierrors.IsConflict(err) {
			logger.V(1).Info("bridge changed since it was checked, re-evaluating", "bridge", key)
			return err
		}
		TranslationErrors.WithLabelValues(ReasonDeleteFailed).Inc()
		logger.Error(err, "unable to delete bridge", "bridge", key)
		return err
	}
	BridgesRemoved.Inc()
	logger.Info("bridge deleted", "bridge", key)
	return nil
}

// bridgeToSource maps a bridge to the source named in its migrated-from annotation, so a bridge
// edited or deleted by hand is restored, and one whose source went away while this controller was
// down is removed at start-up.
func bridgeToSource(ctx context.Context, obj client.Object) []reconcile.Request {
	if obj.GetLabels()[migration.ManagedByLabel] != migration.ComponentName {
		return nil
	}
	source, ok := migration.ParseSourceKey(obj.GetAnnotations()[migration.AnnotationMigratedFrom])
	if !ok {
		log.FromContext(ctx).V(1).Info("bridge has no valid migrated-from annotation, ignoring", "bridge", client.ObjectKeyFromObject(obj))
		return nil
	}
	return []reconcile.Request{{NamespacedName: source}}
}

// SetupWithManager watches legacy PolicyExceptions not generated by kyverno-policy-operator, the
// bridges, and resync events.
func (r *LegacyExceptionReconciler) SetupWithManager(mgr ctrl.Manager, resync <-chan event.GenericEvent) error {
	notKPO := predicate.NewPredicateFuncs(func(obj client.Object) bool { return !migration.IsManagedByKPO(obj) })
	return ctrl.NewControllerManagedBy(mgr).
		Named("legacy-policyexception").
		For(&kyvernov2.PolicyException{}, builder.WithPredicates(notKPO)).
		Watches(&policyAPI.PolicyException{}, handler.EnqueueRequestsFromMapFunc(bridgeToSource)).
		WatchesRawSource(source.Channel(resync, &handler.EnqueueRequestForObject{})).
		Complete(r)
}
