package controller

import (
	"strings"
	"testing"

	"github.com/go-logr/logr"
	"github.com/prometheus/client_golang/prometheus/testutil"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	"github.com/giantswarm/exception-recommender/internal/migration"
)

func TestMigrationCollector(t *testing.T) {
	s := unitScheme(t)
	kpo := named(legacySource("*"), "generated")
	kpo.Labels = map[string]string{migration.ManagedByLabel: migration.KPOComponentName}
	unsupported := named(legacySource("*"), "by-selector")
	unsupported.Spec.Match.Any[0].Selector = &metav1.LabelSelector{}
	// A source that turned lossy after it was bridged: the bridge is kept.
	driftedBridge := existingBridge(ownLabels, "giantswarm/drifted")
	driftedBridge.Name = "drifted-migrated"
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(
		nonrootPolicy(),
		legacySource("*"), existingBridge(ownLabels, "giantswarm/cilium"),
		named(legacySource("*"), "new"),
		named(legacySource("run-as-non-root"), "partial"),
		unsupported,
		named(legacySource("run-as-non-root"), "drifted"), driftedBridge,
		kpo,
	).Build()

	collector := &MigrationCollector{Reader: c, BridgeNamespace: testBridgeNamespace, Log: logr.Discard()}
	expected := `
# HELP exception_recommender_legacy_policyexceptions Legacy kyverno.io PolicyExceptions not generated by kyverno-policy-operator, by migration state.
# TYPE exception_recommender_legacy_policyexceptions gauge
exception_recommender_legacy_policyexceptions{state="collision"} 0
exception_recommender_legacy_policyexceptions{state="lossy"} 2
exception_recommender_legacy_policyexceptions{state="migrated"} 1
exception_recommender_legacy_policyexceptions{state="pending"} 1
exception_recommender_legacy_policyexceptions{state="unsupported"} 1
# HELP exception_recommender_policyexception_migration_info Migration state of each legacy kyverno.io PolicyException. migrated_name is empty unless the source's bridge exists.
# TYPE exception_recommender_policyexception_migration_info gauge
exception_recommender_policyexception_migration_info{migrated_name="",reason="bridge_missing",source_name="new",source_namespace="giantswarm",state="pending"} 1
exception_recommender_policyexception_migration_info{migrated_name="",reason="rule_names",source_name="partial",source_namespace="giantswarm",state="lossy"} 1
exception_recommender_policyexception_migration_info{migrated_name="",reason="selector",source_name="by-selector",source_namespace="giantswarm",state="unsupported"} 1
exception_recommender_policyexception_migration_info{migrated_name="cilium-migrated",reason="",source_name="cilium",source_namespace="giantswarm",state="migrated"} 1
exception_recommender_policyexception_migration_info{migrated_name="drifted-migrated",reason="rule_names",source_name="drifted",source_namespace="giantswarm",state="lossy"} 1
`
	if err := testutil.CollectAndCompare(collector, strings.NewReader(expected)); err != nil {
		t.Fatal(err)
	}
}
