package controller

import (
	"context"
	"time"

	"github.com/go-logr/logr"
	kyvernov2 "github.com/kyverno/kyverno/api/kyverno/v2"
	"github.com/prometheus/client_golang/prometheus"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/giantswarm/exception-recommender/internal/migration"
)

// Values of the translation_errors_total "reason" label.
const (
	ReasonLookupFailed = "lookup_failed"
	ReasonApplyFailed  = "apply_failed"
	ReasonDeleteFailed = "delete_failed"
)

var (
	BridgesRemoved = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "exception_recommender_bridges_removed_total",
		Help: "Migration bridges deleted because their legacy PolicyException was deleted.",
	})
	TranslationErrors = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "exception_recommender_translation_errors_total",
		Help: "Errors looking up policies or bridges, or writing or deleting bridges.",
	}, []string{"reason"})
	LastResync = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "exception_recommender_last_resync_timestamp_seconds",
		Help: "Unix time of the last successful listing of legacy PolicyExceptions from the API server.",
	})
)

var (
	legacyExceptionsDesc = prometheus.NewDesc("exception_recommender_legacy_policyexceptions",
		"Legacy kyverno.io PolicyExceptions not generated by kyverno-policy-operator, by migration state.", []string{"state"}, nil)
	migrationInfoDesc = prometheus.NewDesc("exception_recommender_policyexception_migration_info",
		"Migration state of each legacy kyverno.io PolicyException. migrated_name is empty unless the source's bridge exists.",
		[]string{"source_namespace", "source_name", "migrated_name", "state", "reason"}, nil)
)

// MigrationCollector computes the migration gauges at scrape time with the same Evaluate the
// reconciler uses, so the metrics and the cluster cannot drift apart, even across restarts.
type MigrationCollector struct {
	Reader          client.Reader
	BridgeNamespace string
	Log             logr.Logger
}

func (c *MigrationCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- legacyExceptionsDesc
	ch <- migrationInfoDesc
}

func (c *MigrationCollector) Collect(ch chan<- prometheus.Metric) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	ctx = log.IntoContext(ctx, c.Log)

	var sources kyvernov2.PolicyExceptionList
	if err := c.Reader.List(ctx, &sources); err != nil {
		c.Log.Error(err, "unable to list legacy PolicyExceptions for metrics")
		return
	}

	counts := map[string]int{}
	for _, state := range migration.States {
		counts[state] = 0
	}
	for i := range sources.Items {
		src := &sources.Items[i]
		if migration.IsManagedByKPO(src) {
			continue
		}
		logger := c.Log.WithValues("source", migration.SourceKey(src))
		status, err := migration.Evaluate(log.IntoContext(ctx, logger), c.Reader, c.BridgeNamespace, src)
		if err != nil {
			logger.Error(err, "unable to evaluate legacy PolicyException for metrics")
			continue
		}
		counts[status.State]++
		// migrated_name is set only while the source's own bridge exists. With state lossy or
		// unsupported it marks a bridge kept after the source drifted.
		migratedName := ""
		if status.OwnsBridge(src) {
			migratedName = migration.BridgeName(src)
		}
		ch <- prometheus.MustNewConstMetric(migrationInfoDesc, prometheus.GaugeValue, 1,
			src.Namespace, src.Name, migratedName, status.State, status.Reason)
	}
	for state, n := range counts {
		ch <- prometheus.MustNewConstMetric(legacyExceptionsDesc, prometheus.GaugeValue, float64(n), state)
	}
}
