package controller

import (
	"strings"
	"testing"

	"github.com/go-logr/logr"
	"github.com/prometheus/client_golang/prometheus/testutil"
	"github.com/stretchr/testify/assert"

	"github.com/giantswarm/exception-recommender/internal/migration"
	"github.com/giantswarm/exception-recommender/internal/testsupport"
)

func TestMigrationCollector(t *testing.T) {
	// arrange
	migrated := exactSource()                     // cilium
	drifted := withName(lossySource(), "drifted") // turned lossy after it was bridged: the bridge is kept
	c := newClient(t,
		nonrootPolicy(),
		migrated, bridgeOf(migrated),
		withName(exactSource(), "new"),
		withName(lossySource(), "partial"),
		withName(unsupportedSource(), "by-selector"),
		drifted, bridgeOf(drifted),
		withName(kpoSource(), "generated"),
	)

	collector := &MigrationCollector{Reader: c, BridgeNamespace: testBridgeNamespace, Log: logr.Discard()}
	expected := `
# HELP exception_recommender_legacy_policyexceptions Legacy kyverno.io PolicyExceptions not generated by kyverno-policy-operator, by migration state.
# TYPE exception_recommender_legacy_policyexceptions gauge
exception_recommender_legacy_policyexceptions{state="collision"} 0
exception_recommender_legacy_policyexceptions{state="lossy"} 2
exception_recommender_legacy_policyexceptions{state="migrated"} 1
exception_recommender_legacy_policyexceptions{state="pending"} 1
exception_recommender_legacy_policyexceptions{state="unsupported"} 1
# HELP exception_recommender_policyexception_migration_info Migration state of each legacy kyverno.io PolicyException. migrated_name is empty unless the source's bridge exists.
# TYPE exception_recommender_policyexception_migration_info gauge
exception_recommender_policyexception_migration_info{migrated_name="",reason="bridge_missing",source_name="new",source_namespace="giantswarm",state="pending"} 1
exception_recommender_policyexception_migration_info{migrated_name="",reason="rule_names",source_name="partial",source_namespace="giantswarm",state="lossy"} 1
exception_recommender_policyexception_migration_info{migrated_name="",reason="selector",source_name="by-selector",source_namespace="giantswarm",state="unsupported"} 1
exception_recommender_policyexception_migration_info{migrated_name="cilium-migrated",reason="",source_name="cilium",source_namespace="giantswarm",state="migrated"} 1
exception_recommender_policyexception_migration_info{migrated_name="drifted-migrated",reason="rule_names",source_name="drifted",source_namespace="giantswarm",state="lossy"} 1
`

	// act
	err := testutil.CollectAndCompare(collector, strings.NewReader(expected))

	// assert
	assert.NoError(t, err)
}

// No metrics at all rather than stale ones: alerts must use absent().
func TestMigrationCollectorListFails(t *testing.T) {
	// arrange
	c := newClientWith(t, testsupport.FailList(testsupport.ErrBoom), exactSource())

	collector := &MigrationCollector{Reader: c, BridgeNamespace: testBridgeNamespace, Log: logr.Discard()}

	// act
	n := testutil.CollectAndCount(collector)

	// assert
	assert.Zero(t, n, "metrics collected after a failed list")
}

func TestMigrationCollectorSkipsSourceThatFailsToEvaluate(t *testing.T) {
	// arrange
	broken := withName(exactSource(), "broken")
	c := newClientWith(t, testsupport.FailGetNamed(migration.BridgeName(broken), testsupport.ErrBoom),
		nonrootPolicy(), exactSource(), bridgeOf(exactSource()), broken)

	collector := &MigrationCollector{Reader: c, BridgeNamespace: testBridgeNamespace, Log: logr.Discard()}
	expected := `
# HELP exception_recommender_legacy_policyexceptions Legacy kyverno.io PolicyExceptions not generated by kyverno-policy-operator, by migration state.
# TYPE exception_recommender_legacy_policyexceptions gauge
exception_recommender_legacy_policyexceptions{state="collision"} 0
exception_recommender_legacy_policyexceptions{state="lossy"} 0
exception_recommender_legacy_policyexceptions{state="migrated"} 1
exception_recommender_legacy_policyexceptions{state="pending"} 0
exception_recommender_legacy_policyexceptions{state="unsupported"} 0
# HELP exception_recommender_policyexception_migration_info Migration state of each legacy kyverno.io PolicyException. migrated_name is empty unless the source's bridge exists.
# TYPE exception_recommender_policyexception_migration_info gauge
exception_recommender_policyexception_migration_info{migrated_name="cilium-migrated",reason="",source_name="cilium",source_namespace="giantswarm",state="migrated"} 1
`

	// act
	err := testutil.CollectAndCompare(collector, strings.NewReader(expected))

	// assert
	assert.NoError(t, err)
}
