package controller

import (
	"context"
	"testing"
	"time"

	"github.com/go-logr/logr"
	"github.com/prometheus/client_golang/prometheus/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"sigs.k8s.io/controller-runtime/pkg/event"

	"github.com/giantswarm/exception-recommender/internal/testsupport"
)

func TestResyncerQueuesSourcesAndStampsTime(t *testing.T) {
	// arrange
	api := newClient(t, exactSource(), withName(kpoSource(), "generated"))
	events := make(chan event.GenericEvent, 10)
	LastResync.Set(0)
	r := &Resyncer{APIReader: api, Events: events, Interval: time.Hour, Log: logr.Discard()}

	// act
	r.resync(context.Background())

	// assert
	assert.Len(t, events, 1, "only the source not generated by kyverno-policy-operator is queued")
	assert.NotZero(t, testutil.ToFloat64(LastResync), "last resync timestamp not set")
}

func TestResyncerKeepsTimestampWhenListFails(t *testing.T) {
	// arrange
	api := newClientWith(t, testsupport.FailList(testsupport.ErrBoom))
	events := make(chan event.GenericEvent, 10)
	LastResync.Set(0)
	r := &Resyncer{APIReader: api, Events: events, Interval: time.Hour, Log: logr.Discard()}

	// act
	r.resync(context.Background())

	// assert
	assert.Empty(t, events)
	assert.Zero(t, testutil.ToFloat64(LastResync), "last resync timestamp set after a failed list")
}

func TestResyncerStartResyncsOnEveryTick(t *testing.T) {
	// arrange
	api := newClient(t, exactSource())
	events := make(chan event.GenericEvent)
	ctx, cancel := context.WithCancel(context.Background())
	r := &Resyncer{APIReader: api, Events: events, Interval: time.Millisecond, Log: logr.Discard()}

	// act
	done := make(chan error)
	go func() { done <- r.Start(ctx) }()

	// assert: one event at start, then one per tick
	for i := 0; i < 3; i++ {
		select {
		case <-events:
		case <-time.After(5 * time.Second):
			require.FailNowf(t, "resync not queued", "resync %d", i+1)
		}
	}
	cancel()
	select {
	case err := <-done:
		assert.NoError(t, err)
	case <-time.After(5 * time.Second):
		require.FailNow(t, "Start did not return after the context was cancelled")
	}
}

// The production channel is unbuffered: a controller that stops receiving must not hang the resync.
func TestResyncerStopsWhileBlockedOnQueue(t *testing.T) {
	// arrange
	api := newClient(t, exactSource())
	ctx, cancel := context.WithCancel(context.Background())
	LastResync.Set(0)
	r := &Resyncer{APIReader: api, Events: make(chan event.GenericEvent), Interval: time.Hour, Log: logr.Discard()}

	// act
	done := make(chan struct{})
	go func() {
		r.resync(ctx)
		close(done)
	}()
	cancel()

	// assert
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		require.FailNow(t, "resync blocked after the context was cancelled")
	}
	assert.Zero(t, testutil.ToFloat64(LastResync), "last resync timestamp set for an interrupted resync")
}
