name: exception-recommender
serviceType: managed

global:
  image:
    registry: "gsoci.azurecr.io"
  # Install PSPs
  podSecurityStandards:
    enforced: true

cleanupJob:
  enabled: true

ciliumNetworkPolicy:
  enabled: true

image:
  registry: gsoci.azurecr.io
  name: giantswarm/exception-recommender
  pullPolicy: IfNotPresent

# We install CRDs through a Job with the helm specific crd folder.
crds:
  install: true
  image:
    tag: "1.27.4"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

nodeSelector: {}
tolerations: []

# Additional custom pod labels
podLabels: {}

# Pod securityContext
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 100m
    memory: 220Mi

recommender:
  # Install PolicyExceptionDrafts on the giantswarm namespace
  destinationNamespace: policy-exceptions
  targetWorkloads:
    - Deployment
    - DaemonSet
    - StatefulSet
    - CronJob
  targetCategories:
    - Pod Security Standards (Baseline)
    - Pod Security Standards (Restricted)
    - Pod Security Standards
  excludeNamespaces:
    - kube-system
    - giantswarm
  createNamespace: false
