{{- if and .Values.recommender.createNamespace .Values.recommender.destinationNamespace }}
{{- if not (lookup "v1" "Namespace" "" "policy-exceptions")}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.recommender.destinationNamespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- end }}
{{- end }}
